version: '3'

services:
    frontend:
        image: staticfloat/nginx-certbot:1.1
        restart: always
        env_file:
            - .env
        ports:
            - 80:80/tcp
            - 443:443/tcp
        volumes:
            - ./sites-available:/etc/nginx/user.conf.d/:ro
            - letsencrypt:/etc/letsencrypt

networks:
    default:
        external:
            name: nginx

volumes:
    letsencrypt:
